name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --release
      - name: Package binaries
        run: |
          mkdir dist
          cp target/release/unit-forge-cli dist/
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/unit-forge-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
